apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  creationTimestamp: null
  name: api
spec:
  build:
    buildpacks: {}
    path: ../api
    nonSecretEnv:
      - name: "BP_JVM_VERSION"
        value: "17"
  ports:
  - name: main
    port: 8080
