apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  creationTimestamp: null
  name: single-image-multi-app
spec:
  build:
    buildpacks: {}
    path: ..
    nonSecretEnv:
    - name: BP_JVM_VERSION
      value: "17"
    - name: BP_JAVA_INSTALL_NODE
      value: "true"
    - name: BP_NODE_PROJECT_PATH
      value: "frontend"
  ports:
  - name: main
    port: 8080
