apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  creationTimestamp: null
  name: notify
spec:
  build:
    buildpacks: {}
    path: ../where-for-dinner-notify
    nonSecretEnv:
    - name: BP_JVM_VERSION
      value: "21"
  ports:
  - name: main
    port: 8080
