apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  creationTimestamp: null
  name: ui
spec:
  build:
    buildpacks: {}
    path: ../where-for-dinner-ui
    nonSecretEnv:
    - name: BP_NODE_RUN_SCRIPTS
      value: build
    - name: BP_WEB_SERVER_ROOT
      value: dist
  ports:
    - name: main
      port: 8080
  nonSecretEnv:
    - name: PORT
      value: "8080"
